"""empty message

Revision ID: 502dca86b11c
Revises: 
Create Date: 2022-04-24 18:11:17.493204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502dca86b11c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('Sno', sa.Integer(), nullable=False),
    sa.Column('EmpName', sa.String(length=20), nullable=True),
    sa.Column('EmpSalary', sa.Float(), nullable=True),
    sa.Column('EmpId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Sno')
    )
    op.create_table('EmpTechArea',
    sa.Column('Sno', sa.Integer(), nullable=False),
    sa.Column('TechArea', sa.String(length=15), nullable=True),
    sa.Column('EmpId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EmpId'], ['Company.EmpId'], ),
    sa.PrimaryKeyConstraint('Sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EmpTechArea')
    op.drop_table('Company')
    # ### end Alembic commands ###
